"""empty message

Revision ID: 1a11dd4da10e
Revises: 2ce636a352f6
Create Date: 2025-12-18 08:51:28.757814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a11dd4da10e'
down_revision = '2ce636a352f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proctoring_logs', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_column('proctoring_logs')

    # ### end Alembic commands ###
