"""empty message

Revision ID: 2ce636a352f6
Revises: ec9d6a359f88
Create Date: 2025-12-18 05:43:44.104572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ce636a352f6'
down_revision = 'ec9d6a359f88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_minutes', sa.Integer(), nullable=False))

    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_started', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('results', schema=None) as batch_op:
        batch_op.drop_column('time_started')

    with op.batch_alter_table('question_papers', schema=None) as batch_op:
        batch_op.drop_column('duration_minutes')

    # ### end Alembic commands ###
